version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"         # Cola
      - "15672:15672"       # UI de administración
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: academic
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - academic-management
    volumes:
      - ./api-gateway:/app
    env_file:
      - .env

  academic-management:
    build: ./services/academic-management
    container_name: academic-management
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./services/academic-management:/app
    env_file:
      - .env

  prediction-service:
    build:
      context: ./services/prediction-service
    container_name: prediction-service
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
    volumes:
      - ./services/prediction-service:/app 

  prediction-consumer:
    build:
      context: ./services/prediction-service
    container_name: prediction-consumer
    depends_on:
      - rabbitmq
    command: python app/consumer/consumer.py
    volumes:
      - ./services/prediction-service:/app




volumes:
  postgres-data:
